overrides:
  - files:
      - "*.js"
      - "*.jsx"
      - "*.html"
      - "*.css"
    options:
      printWidth: 120
      tabWidth: 2
      useTabs: false
      semi: true
      singleQuote: true
      quoteProps: as-needed
      jsxSingleQuote: true
      trailingComma: 'all'
      bracketSpacing: true
      jsxBracketSameLine: true
      arrowParens: avoid
      requirePragma: false
      insertPragma: false
      htmlWhitespaceSensitivity: strict
      endOfLine: lf
